3 | Add webpack node babel server
dario92/burritojs pull request #5
Opened 2016-11-05 13:40 UTC by cav2008

2016-11-07 17:27 UTC, dario92 requested changes
Hey good job man! :) 
But you haven't plugged webpack 😄

2016-11-07 17:27 UTC, dario92 commented on package.json
> +  "directories": {
What is this property for ? 😄

2016-11-07 17:27 UTC, dario92 commented on package.json
> +    "install": "^0.8.2",
Why we need this ?

2016-11-07 17:27 UTC, dario92 commented on package.json
> +    "webpack": "^1.13.3"
Hey let's try to use `webpack 2` it has tree shaking.

2016-11-16 19:18 UTC, cav2008 commented on package.json
> +  "directories": {
@dario92 I dunno it was when you do npm init lol. Do you want me to delete this part?

2016-11-16 19:35 UTC, cav2008 commented on package.json
> +    "install": "^0.8.2",
@dario92 isn't this for the babel node lol?

2016-11-16 19:37 UTC, cav2008 commented on package.json
> +    "webpack": "^1.13.3"
@dario92 ok cool I will install webpack 2

2016-11-24 17:23 UTC, cav2008 commented
@dario92 I added the changes. But I don't understand what you mean I haven't plugged webpack

2018-05-30 11:27 UTC, closed without merging